### ISSUE TITLE
Installation from web interface

### ISSUE THREAD

**Issue by earboxer** [civicrm/org.civicrm.doctorwhen#19]
With command line installation, it is easy to get file permissions wrong, which can make non-cli uninstallation difficult.

If this extension is stable enough to be recommended, perhaps it should be able to be installed from the extensions page.

**Comment by mlutfy** [comment]
@totten Still is still relevant, right? I can create the extension on c.o.

**Comment by kurund** [comment]
@mlutfy This is still relevant if the installs have not fixed the date changes / ignored it so far. So might be good to have it on c.o

**Comment by mlutfy** [comment]
Thanks @kurund. I think so too. I took the liberty of publishing the release: https://civicrm.org/extensions/doctorwhen

(and also tagged 1.1 in the git repo)
