### ISSUE TITLE
Timestamp conversion fails on MySQL 5.7

### ISSUE THREAD

**Issue by MegaphoneJon** [civicrm/org.civicrm.doctorwhen#5]
By default, MySQL 5.7's SQL modes include "NO_ZERO_DATE" and "NO_ZERO_IN_DATE".  When these SQL modes are set, `CRM_DoctorWhen_Cleanups_ConvertTimestamp->enqueue()` doesn't specify valid default values when `$this->default` is `null`.

This leads to this error on objects where `$this->default` is `null`:
[ERROR 1067 (42000): Invalid default value for](https://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at) 'expired_date'.

**Comment by totten** [comment]
Related question on Mattermost: https://chat.civicrm.org/civicrm/pl/wm59uhmrojrsjfzowii6e79r8w

**Comment by seamuslee001** [comment]
I believe that the combination of https://github.com/civicrm/org.civicrm.doctorwhen/pull/6 and https://github.com/civicrm/civicrm-core/pull/11129 will fix the conversion
